### PR TITLE
Add support for async batch rpc calls

### PR DESCRIPTION
**Pull request by bumi**
Even though this is not specified in EIP-1193 at least web3.js v0.x is calling the sendAsyc function with an array of rpc calls.
To be compatible this adds support for such async batch calls.

Example:
```js
sendAsync([ { jsonrpc: '2.0', id: 6, method: 'eth_getFilterChanges', params: [ '0x0' ] } ], callback) 
// callback will be called with an array of results e.g.: [ { jsonrpc: '2.0', id: 6, result: ['whatever'] } ]
```
I am not super happy with the code and maybe we would want to move the default behaviour (with a single object as payload) also in a function? But I did not want to change too much :) 

In my tests everything worked fine. but as we don't have any unit tests here, please review carefully. I don't know the code very well and maybe I am missing something. :) 

related issue: https://github.com/floating/ethereum-provider/issues/2

### CODE REVIEW

**Comment by floating** [comment]
Thanks @bumi! This looks good to me. I've expanded the `eth-provider` tests to cover batches and have tested this pull request across web3 v0.x and v1.x. I agree adding standalone unit tests here would be helpful though.

**Comment by bumi** [comment]
ok, awesome! thanks a lot!! 
I will see if I can find some time to add some tests here.

**Comment by floating** [comment]
Awesome, thanks again! I'm working on a few other updates to `eth-provider` before  publishing the next version but this will be included when I do.

**Comment by floating** [comment]
@bumi eth-provider `v0.2.2` and ethereum-provider `v0.0.6` just published!

**Pull request merged**
